### ISSUE TITLE
Name is not staying in game scene

### ISSUE THREAD

**Issue by SunixDev** [insthync/BattleIOMasterServer#1]
Player name is not working when it enter game scene the go to Guess_XXXX

**Comment by insthync** [comment]
@SunixDev Thank you for your report the issue have been fixed, check out the latest version

**Comment by SunixDev** [comment]
OK thank you i will check it mater , i also notices i wasnt saving current selmt also .
Thanks 
Regards

**Comment by SunixDev** [comment]
It wasnt saving the current character equipment set*

**Comment by SunixDev** [comment]
Ok its working . So its good 
Thank you
